// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Represents the enum public.invoice_status */
enum InvoiceStatus {
  PAID = 'PAID',
  UNPAID = 'UNPAID',
  PENDING = 'PENDING',
  CANCELLED = 'CANCELLED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
  EXPIRED = 'EXPIRED',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
};

export default InvoiceStatus;
