// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as InvoiceStatus } from './InvoiceStatus';
import type { ColumnType, Selectable, Insertable, Updateable } from 'kysely';

/** Identifier type for public.invoices */
export type InvoicesId = string & { __brand: 'InvoicesId' };

/** Represents the table public.invoices */
export default interface InvoicesTable {
  id: ColumnType<InvoicesId, InvoicesId | undefined, InvoicesId>;

  invoice_number: ColumnType<string, string, string>;

  name: ColumnType<string, string, string>;

  amount: ColumnType<number, number, number>;

  status: ColumnType<InvoiceStatus, InvoiceStatus, InvoiceStatus>;

  created_at: ColumnType<Date, Date | string | undefined, Date | string>;

  updated_at: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Invoices = Selectable<InvoicesTable>;

export type NewInvoices = Insertable<InvoicesTable>;

export type InvoicesUpdate = Updateable<InvoicesTable>;
