// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { default as InvoicesTable } from './Invoices';
import type { default as KyselyMigrationLockTable } from './KyselyMigrationLock';
import type { default as KyselyMigrationTable } from './KyselyMigration';

export default interface PublicSchema {
  invoices: InvoicesTable;

  kysely_migration_lock: KyselyMigrationLockTable;

  kysely_migration: KyselyMigrationTable;
}
